"""
Verbose Logging Service with Markdown Documentation
Captures all prompts and valuable outcomes for documentation
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional
import hashlib
import yaml

class VerboseLogger:
    """Enhanced logger for capturing prompts and generating documentation"""
    
    def __init__(self, docs_path: str = "/Users/scottderozic/dev/ai/docs"):
        self.docs_path = Path(docs_path)
        self.docs_path.mkdir(parents=True, exist_ok=True)
        
        # Create subdirectories
        self.prompts_dir = self.docs_path / "prompts"
        self.responses_dir = self.docs_path / "responses"
        self.workflows_dir = self.docs_path / "workflows"
        self.insights_dir = self.docs_path / "insights"
        
        for dir_path in [self.prompts_dir, self.responses_dir, self.workflows_dir, self.insights_dir]:
            dir_path.mkdir(exist_ok=True)
        
        # Setup logging
        self.logger = logging.getLogger("ai_orchestrator")
        self.logger.setLevel(logging.DEBUG)
        
        # Console handler
        ch = logging.StreamHandler()
        ch.setLevel(logging.INFO)
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        ch.setFormatter(formatter)
        self.logger.addHandler(ch)
        
        # File handler for verbose logs
        log_file = self.docs_path / "verbose.log"
        fh = logging.FileHandler(log_file)
        fh.setLevel(logging.DEBUG)
        fh.setFormatter(formatter)
        self.logger.addHandler(fh)
    
    def log_prompt(self, prompt: str, task_type: str, model: str, metadata: Dict[str, Any] = None) -> str:
        """Log a prompt to markdown file"""
        timestamp = datetime.now()
        prompt_id = self._generate_id(prompt)
        
        # Create markdown file
        filename = f"{timestamp.strftime('%Y%m%d_%H%M%S')}_{prompt_id[:8]}.md"
        filepath = self.prompts_dir / filename
        
        content = f"""# Prompt Log

**Date**: {timestamp.strftime('%Y-%m-%d %H:%M:%S')}
**ID**: {prompt_id}
**Task Type**: {task_type}
**Model**: {model}

## Prompt

```
{prompt}
```

## Metadata

```yaml
{yaml.dump(metadata or {}, default_flow_style=False)}
```

---
Generated by AI Orchestrator
"""
        
        filepath.write_text(content)
        self.logger.debug(f"Logged prompt to {filename}")
        
        return prompt_id
    
    def log_response(self, prompt_id: str, response: Dict[str, Any], execution_time: float) -> None:
        """Log a valuable response to markdown file"""
        timestamp = datetime.now()
        
        # Determine if response is valuable
        if not self._is_valuable_response(response):
            return
        
        filename = f"{timestamp.strftime('%Y%m%d_%H%M%S')}_response_{prompt_id[:8]}.md"
        filepath = self.responses_dir / filename
        
        # Extract key information
        content = f"""# Response Log

**Date**: {timestamp.strftime('%Y-%m-%d %H:%M:%S')}
**Prompt ID**: {prompt_id}
**Execution Time**: {execution_time:.2f}s
**Model**: {response.get('model', 'Unknown')}
**Task Type**: {response.get('task_type', 'Unknown')}

## Result

"""
        
        # Format response based on type
        if response.get('code'):
            content += f"""### Generated Code

```{self._detect_language(response['code'])}
{response['code']}
```

"""
        
        if response.get('reasoning'):
            content += f"""### Reasoning

{response['reasoning']}

"""
        
        if response.get('answer'):
            content += f"""### Answer

{response['answer']}

"""
        
        if response.get('approach'):
            content += f"""### Approach

{response['approach']}

"""
        
        if response.get('explanation'):
            content += f"""### Explanation

{response['explanation']}

"""
        
        content += """
---
Generated by AI Orchestrator
"""
        
        filepath.write_text(content)
        self.logger.info(f"Logged valuable response to {filename}")
    
    def log_workflow(self, workflow_name: str, steps: list, results: list) -> None:
        """Log a complete workflow execution"""
        timestamp = datetime.now()
        workflow_id = self._generate_id(workflow_name)
        
        filename = f"{timestamp.strftime('%Y%m%d_%H%M%S')}_workflow_{workflow_id[:8]}.md"
        filepath = self.workflows_dir / filename
        
        content = f"""# Workflow Execution: {workflow_name}

**Date**: {timestamp.strftime('%Y-%m-%d %H:%M:%S')}
**Workflow ID**: {workflow_id}
**Total Steps**: {len(steps)}

## Workflow Diagram

```mermaid
graph TD
"""
        
        # Generate Mermaid diagram
        for i, step in enumerate(steps):
            next_step = steps[i + 1] if i < len(steps) - 1 else None
            content += f"    Step{i}[{step['name']}]\n"
            if next_step:
                content += f"    Step{i} --> Step{i+1}\n"
        
        content += """```

## Execution Steps

"""
        
        # Document each step
        for i, (step, result) in enumerate(zip(steps, results)):
            content += f"""### Step {i+1}: {step['name']}

**Connector**: {step.get('connector', 'N/A')}
**Action**: {step.get('action', 'N/A')}
**Status**: {result.get('status', 'Unknown')}

"""
            if result.get('output'):
                content += f"""**Output**:
```json
{json.dumps(result['output'], indent=2)}
```

"""
        
        content += """
---
Generated by AI Orchestrator
"""
        
        filepath.write_text(content)
        self.logger.info(f"Logged workflow to {filename}")
    
    def generate_daily_summary(self) -> None:
        """Generate daily summary documentation"""
        today = datetime.now().date()
        summary_file = self.insights_dir / f"daily_summary_{today}.md"
        
        # Collect statistics
        prompts_today = len(list(self.prompts_dir.glob(f"{today.strftime('%Y%m%d')}*.md")))
        responses_today = len(list(self.responses_dir.glob(f"{today.strftime('%Y%m%d')}*.md")))
        workflows_today = len(list(self.workflows_dir.glob(f"{today.strftime('%Y%m%d')}*.md")))
        
        content = f"""# Daily Summary - {today}

## Statistics

- **Total Prompts**: {prompts_today}
- **Valuable Responses**: {responses_today}
- **Workflows Executed**: {workflows_today}

## Key Insights

### Most Used Models
- [Analysis pending]

### Task Distribution
- [Analysis pending]

### Performance Metrics
- [Analysis pending]

## Recent Files

### Prompts
"""
        
        # List recent prompt files
        recent_prompts = sorted(self.prompts_dir.glob(f"{today.strftime('%Y%m%d')}*.md"))[-5:]
        for filepath in recent_prompts:
            content += f"- [{filepath.name}](../prompts/{filepath.name})\n"
        
        content += """

### Responses
"""
        
        recent_responses = sorted(self.responses_dir.glob(f"{today.strftime('%Y%m%d')}*.md"))[-5:]
        for filepath in recent_responses:
            content += f"- [{filepath.name}](../responses/{filepath.name})\n"
        
        content += """

---
Generated by AI Orchestrator
"""
        
        summary_file.write_text(content)
        self.logger.info(f"Generated daily summary for {today}")
    
    def _generate_id(self, content: str) -> str:
        """Generate unique ID from content"""
        return hashlib.md5(content.encode()).hexdigest()
    
    def _is_valuable_response(self, response: Dict[str, Any]) -> bool:
        """Determine if a response is valuable enough to log"""
        # Log if it contains code, detailed reasoning, or complex outputs
        valuable_keys = ['code', 'reasoning', 'design', 'api_spec', 'configuration']
        return any(key in response for key in valuable_keys) and 'error' not in response
    
    def _detect_language(self, code: str) -> str:
        """Detect programming language from code"""
        if 'def ' in code or 'import ' in code:
            return 'python'
        elif 'function ' in code or 'const ' in code or 'let ' in code:
            return 'javascript'
        elif 'interface ' in code or ': string' in code:
            return 'typescript'
        elif '<?php' in code:
            return 'php'
        elif 'public class' in code:
            return 'java'
        else:
            return 'text'