'use client'

import { useState, useEffect } from 'react'
import Logo from '@/components/Logo'
import { GradientMesh } from '@/components/GradientMesh'
import Link from 'next/link'

interface APIKey {
  provider: string
  key: string
  lastRotated: string
  isActive: boolean
}

interface Connector {
  id: string
  name: string
  icon: string
  status: 'connected' | 'disconnected' | 'pending'
  lastSync: string | null
  description: string
}

export default function Settings() {
  const [activeTab, setActiveTab] = useState<'api-keys' | 'connectors' | 'logging'>('api-keys')
  const [apiKeys, setApiKeys] = useState<APIKey[]>([
    { provider: 'OpenAI', key: '', lastRotated: 'Never', isActive: false },
    { provider: 'Anthropic', key: '', lastRotated: 'Never', isActive: false },
    { provider: 'Google Gemini', key: '', lastRotated: 'Never', isActive: false },
  ])
  
  const [connectors] = useState<Connector[]>([
    { id: 'clickup', name: 'ClickUp', icon: '📋', status: 'disconnected', lastSync: null, description: 'Task management and productivity' },
    { id: 'github', name: 'GitHub', icon: '🐙', status: 'disconnected', lastSync: null, description: 'Code repository and collaboration' },
    { id: 'google-workspace', name: 'Google Workspace', icon: '📧', status: 'disconnected', lastSync: null, description: 'Email, docs, and calendar' },
    { id: 'todoist', name: 'Todoist', icon: '✅', status: 'disconnected', lastSync: null, description: 'Personal task management' },
    { id: 'linear', name: 'Linear', icon: '📊', status: 'disconnected', lastSync: null, description: 'Issue tracking for teams' },
    { id: 'notion', name: 'Notion', icon: '📝', status: 'disconnected', lastSync: null, description: 'Knowledge base and notes' },
    { id: 'discord', name: 'Discord', icon: '💬', status: 'disconnected', lastSync: null, description: 'Team communication' },
  ])

  const [loggingSettings, setLoggingSettings] = useState({
    verboseMode: true,
    savePrompts: true,
    saveResponses: true,
    autoGenerateDocs: true,
    logLevel: 'info'
  })

  const handleApiKeyUpdate = (provider: string, key: string) => {
    setApiKeys(prev => prev.map(k => 
      k.provider === provider 
        ? { ...k, key, lastRotated: new Date().toLocaleDateString(), isActive: key.length > 0 }
        : k
    ))
  }

  const handleRotateKey = async (provider: string) => {
    // Implement key rotation logic
    console.log(`Rotating key for ${provider}`)
  }

  const handleConnectorToggle = async (connectorId: string) => {
    // Implement OAuth flow for connector
    console.log(`Toggling connector: ${connectorId}`)
  }

  return (
    <div className="min-h-screen bg-gray-950 text-white relative overflow-hidden">
      <GradientMesh />
      
      <div className="relative z-10">
        <div className="container mx-auto px-4 py-6">
          <header className="mb-8 border-b border-gray-800 pb-6">
            <div className="flex items-center justify-between">
              <Logo />
              <Link 
                href="/"
                className="px-4 py-2 bg-gray-800/50 backdrop-blur rounded-lg text-sm hover:bg-gray-700/50 transition"
              >
                Back to Dashboard
              </Link>
            </div>
          </header>

          <div className="max-w-6xl mx-auto">
            <h1 className="text-3xl font-bold mb-8">Settings</h1>
            
            {/* Tab Navigation */}
            <div className="flex gap-4 mb-8 border-b border-gray-800">
              <button
                onClick={() => setActiveTab('api-keys')}
                className={`pb-4 px-2 font-medium transition ${
                  activeTab === 'api-keys' 
                    ? 'text-blue-400 border-b-2 border-blue-400' 
                    : 'text-gray-400 hover:text-white'
                }`}
              >
                API Keys
              </button>
              <button
                onClick={() => setActiveTab('connectors')}
                className={`pb-4 px-2 font-medium transition ${
                  activeTab === 'connectors' 
                    ? 'text-blue-400 border-b-2 border-blue-400' 
                    : 'text-gray-400 hover:text-white'
                }`}
              >
                Connectors
              </button>
              <button
                onClick={() => setActiveTab('logging')}
                className={`pb-4 px-2 font-medium transition ${
                  activeTab === 'logging' 
                    ? 'text-blue-400 border-b-2 border-blue-400' 
                    : 'text-gray-400 hover:text-white'
                }`}
              >
                Logging & Docs
              </button>
            </div>

            {/* API Keys Tab */}
            {activeTab === 'api-keys' && (
              <div className="space-y-6">
                <div className="bg-gray-800/50 backdrop-blur rounded-lg p-6">
                  <h2 className="text-xl font-semibold mb-4">API Key Management</h2>
                  <p className="text-gray-400 text-sm mb-6">
                    Configure your API keys for paid providers. Keys are encrypted and stored securely.
                  </p>
                  
                  <div className="space-y-4">
                    {apiKeys.map((apiKey) => (
                      <div key={apiKey.provider} className="bg-gray-900/50 rounded-lg p-4">
                        <div className="flex items-center justify-between mb-3">
                          <div className="flex items-center gap-3">
                            <h3 className="font-medium">{apiKey.provider}</h3>
                            <span className={`text-xs px-2 py-1 rounded ${
                              apiKey.isActive 
                                ? 'bg-green-500/20 text-green-400' 
                                : 'bg-gray-600/20 text-gray-400'
                            }`}>
                              {apiKey.isActive ? 'Active' : 'Inactive'}
                            </span>
                          </div>
                          <button
                            onClick={() => handleRotateKey(apiKey.provider)}
                            className="text-sm text-blue-400 hover:text-blue-300"
                          >
                            Rotate Key
                          </button>
                        </div>
                        
                        <div className="flex gap-2">
                          <input
                            type="password"
                            value={apiKey.key}
                            onChange={(e) => handleApiKeyUpdate(apiKey.provider, e.target.value)}
                            placeholder="Enter API key..."
                            className="flex-1 px-3 py-2 bg-gray-800 rounded border border-gray-700 focus:border-blue-500 focus:outline-none"
                          />
                        </div>
                        
                        <div className="mt-2 text-xs text-gray-500">
                          Last rotated: {apiKey.lastRotated}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* Connectors Tab */}
            {activeTab === 'connectors' && (
              <div className="space-y-6">
                <div className="bg-gray-800/50 backdrop-blur rounded-lg p-6">
                  <h2 className="text-xl font-semibold mb-4">Service Connectors</h2>
                  <p className="text-gray-400 text-sm mb-6">
                    Connect to external services for seamless workflow automation.
                  </p>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {connectors.map((connector) => (
                      <div key={connector.id} className="bg-gray-900/50 rounded-lg p-4">
                        <div className="flex items-start justify-between">
                          <div className="flex items-start gap-3">
                            <span className="text-2xl">{connector.icon}</span>
                            <div>
                              <h3 className="font-medium">{connector.name}</h3>
                              <p className="text-xs text-gray-400 mt-1">
                                {connector.description}
                              </p>
                              {connector.lastSync && (
                                <p className="text-xs text-gray-500 mt-2">
                                  Last sync: {connector.lastSync}
                                </p>
                              )}
                            </div>
                          </div>
                          
                          <button
                            onClick={() => handleConnectorToggle(connector.id)}
                            className={`px-3 py-1 rounded text-sm transition ${
                              connector.status === 'connected'
                                ? 'bg-green-500/20 text-green-400 hover:bg-green-500/30'
                                : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
                            }`}
                          >
                            {connector.status === 'connected' ? 'Connected' : 'Connect'}
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* Logging Tab */}
            {activeTab === 'logging' && (
              <div className="space-y-6">
                <div className="bg-gray-800/50 backdrop-blur rounded-lg p-6">
                  <h2 className="text-xl font-semibold mb-4">Logging & Documentation</h2>
                  <p className="text-gray-400 text-sm mb-6">
                    Configure verbose logging and automatic documentation generation.
                  </p>
                  
                  <div className="space-y-4">
                    <label className="flex items-center justify-between p-3 bg-gray-900/50 rounded-lg">
                      <div>
                        <div className="font-medium">Verbose Mode</div>
                        <div className="text-xs text-gray-400">Log detailed information about all operations</div>
                      </div>
                      <input
                        type="checkbox"
                        checked={loggingSettings.verboseMode}
                        onChange={(e) => setLoggingSettings({...loggingSettings, verboseMode: e.target.checked})}
                        className="w-5 h-5"
                      />
                    </label>
                    
                    <label className="flex items-center justify-between p-3 bg-gray-900/50 rounded-lg">
                      <div>
                        <div className="font-medium">Save Prompts</div>
                        <div className="text-xs text-gray-400">Store all prompts in the docs directory</div>
                      </div>
                      <input
                        type="checkbox"
                        checked={loggingSettings.savePrompts}
                        onChange={(e) => setLoggingSettings({...loggingSettings, savePrompts: e.target.checked})}
                        className="w-5 h-5"
                      />
                    </label>
                    
                    <label className="flex items-center justify-between p-3 bg-gray-900/50 rounded-lg">
                      <div>
                        <div className="font-medium">Save Responses</div>
                        <div className="text-xs text-gray-400">Store valuable outcomes as markdown files</div>
                      </div>
                      <input
                        type="checkbox"
                        checked={loggingSettings.saveResponses}
                        onChange={(e) => setLoggingSettings({...loggingSettings, saveResponses: e.target.checked})}
                        className="w-5 h-5"
                      />
                    </label>
                    
                    <label className="flex items-center justify-between p-3 bg-gray-900/50 rounded-lg">
                      <div>
                        <div className="font-medium">Auto-Generate Documentation</div>
                        <div className="text-xs text-gray-400">Automatically create VuePress documentation</div>
                      </div>
                      <input
                        type="checkbox"
                        checked={loggingSettings.autoGenerateDocs}
                        onChange={(e) => setLoggingSettings({...loggingSettings, autoGenerateDocs: e.target.checked})}
                        className="w-5 h-5"
                      />
                    </label>
                    
                    <div className="p-3 bg-gray-900/50 rounded-lg">
                      <label className="block mb-2">
                        <div className="font-medium mb-2">Log Level</div>
                        <select
                          value={loggingSettings.logLevel}
                          onChange={(e) => setLoggingSettings({...loggingSettings, logLevel: e.target.value})}
                          className="w-full px-3 py-2 bg-gray-800 rounded border border-gray-700 focus:border-blue-500 focus:outline-none"
                        >
                          <option value="error">Error</option>
                          <option value="warn">Warning</option>
                          <option value="info">Info</option>
                          <option value="debug">Debug</option>
                        </select>
                      </label>
                    </div>
                  </div>
                  
                  <div className="mt-6 p-4 bg-blue-500/10 rounded-lg border border-blue-500/30">
                    <div className="flex items-center gap-3">
                      <svg className="w-5 h-5 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      <div className="text-sm">
                        <div className="font-medium text-blue-400">Documentation Path</div>
                        <div className="text-gray-400">/Users/scottderozic/dev/ai/docs</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}